# config/comparison.yaml

jobs:
  - name: "Quick Test: iOS Stg v2 vs Prod v1"
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    quickMode: true
    endpointPairs:
      - endpointA: "matches-live-v1"
        endpointB: "matches-live-v2"
      - endpointA: "matches-recent-v1"
        endpointB: "matches-recent-v2"
      - endpointA: "matches-upcoming-v1"
        endpointB: "matches-upcoming-v2"
      - endpointA: "matches-current-v1"
        endpointB: "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 1
      delayMs: 1000

  - name: "iOS: Stg v2 vs Prod v1 (explicit pairs)"
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "matches-live-v1"
        endpointB: "matches-live-v2"
      - endpointA: "matches-recent-v1"
        endpointB: "matches-recent-v2"
      - endpointA: "matches-upcoming-v1"
        endpointB: "matches-upcoming-v2"
      - endpointA: "matches-current-v1"
        endpointB: "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Android: Stg v2 vs Prod v1 (explicit pairs)"
    platform: "a"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "matches-live-v1"
        endpointB: "matches-live-v2"
      - endpointA: "matches-recent-v1"
        endpointB: "matches-recent-v2"
      - endpointA: "matches-upcoming-v1"
        endpointB: "matches-upcoming-v2"
      - endpointA: "matches-current-v1"
        endpointB: "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Mobile-Web: Stg v2 vs Prod v1 (explicit pairs)"
    platform: "m"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "matches-live-v1"
        endpointB: "matches-live-v2"
      - endpointA: "matches-recent-v1"
        endpointB: "matches-recent-v2"
      - endpointA: "matches-upcoming-v1"
        endpointB: "matches-upcoming-v2"
      - endpointA: "matches-current-v1"
        endpointB: "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Desktop-Web: Stg v2 vs Prod v1 (explicit pairs)"
    platform: "w"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "matches-live-v1"
        endpointB: "matches-live-v2"
      - endpointA: "matches-recent-v1"
        endpointB: "matches-recent-v2"
      - endpointA: "matches-upcoming-v1"
        endpointB: "matches-upcoming-v2"
      - endpointA: "matches-current-v1"
        endpointB: "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

