# config/comparison.yaml

jobs:
  # Quick test job - only first ID, first geo location
  - name: "Quick Test: iOS Prod v1 vs Stg v2"  
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    quickMode: true
    endpointsToRun:
      - "matches-live-v1"
      - "matches-recent-v1"
      - "matches-upcoming-v1"
      - "matches-current-v1"
      - "matches-live-v2"
      - "matches-recent-v2"
      - "matches-upcoming-v2"
      - "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 1
      delayMs: 1000

  - name: "iOS: Prod v1 vs Stg v2 (match endpoints)"
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointsToRun:
      - "matches-live-v1"
      - "matches-recent-v1"
      - "matches-upcoming-v1"
      - "matches-current-v1"
      - "matches-live-v2"
      - "matches-recent-v2"
      - "matches-upcoming-v2"
      - "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Android: Prod v1 vs Stg v2 (match endpoints)"
    platform: "a"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointsToRun:
      - "matches-live-v1"
      - "matches-recent-v1"
      - "matches-upcoming-v1"
      - "matches-current-v1"
      - "matches-live-v2"
      - "matches-recent-v2"
      - "matches-upcoming-v2"
      - "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Mobile-Web: Prod v1 vs Stg v2 (match endpoints)"
    platform: "m"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointsToRun:
      - "matches-live-v1"
      - "matches-recent-v1"
      - "matches-upcoming-v1"
      - "matches-current-v1"
      - "matches-live-v2"
      - "matches-recent-v2"
      - "matches-upcoming-v2"
      - "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Desktop-Web: Prod v1 vs Stg v2 (match endpoints)"
    platform: "w"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointsToRun:
      - "matches-live-v1"
      - "matches-recent-v1"
      - "matches-upcoming-v1"
      - "matches-current-v1"
      - "matches-live-v2"
      - "matches-recent-v2"
      - "matches-upcoming-v2"
      - "matches-current-v2"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000
