# config/comparison.yaml

jobs:
  - name: "Quick Test: iOS Stg vs Prod"
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    quickMode: true
    endpointPairs:
      - endpointA: "venue-details-v1"
        endpointB: "venue-details-stg"
      - endpointA: "venue-matches-v1"
        endpointB: "venue-matches-stg"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 1
      delayMs: 1000

  - name: "iOS: Stg vs Prod (explicit pairs)"
    platform: "i"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "venue-details-v1"
        endpointB: "venue-details-stg"
      - endpointA: "venue-matches-v1"
        endpointB: "venue-matches-stg"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Android: Stg vs Prod (explicit pairs)"
    platform: "a"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "venue-details-v1"
        endpointB: "venue-details-stg"
      - endpointA: "venue-matches-v1"
        endpointB: "venue-matches-stg"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Mobile-Web: Stg vs Prod (explicit pairs)"
    platform: "m"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "venue-details-v1"
        endpointB: "venue-details-stg"
      - endpointA: "venue-matches-v1"
        endpointB: "venue-matches-stg"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

  - name: "Desktop-Web: Stg vs Prod (explicit pairs)"
    platform: "w"
    baseA: "https://apiserver.cricbuzz.com"
    baseB: "http://api.cricbuzz.stg"
    endpointPairs:
      - endpointA: "venue-details-v1"
        endpointB: "venue-details-stg"
      - endpointA: "venue-matches-v1"
        endpointB: "venue-matches-stg"
    ignorePaths:
      - "meta.timestamp"
      - "data.generatedId"
    retryPolicy:
      retries: 2
      delayMs: 2000

